### ISSUE TITLE
Patch Moodle 4.4.1

### ISSUE THREAD

**Issue by neeesn** [praxisdigital/moodle-kslaring#2]
@frederikmillingpytlick it is time for yet another patch for KS for Moodle update 4.4.1
I have made a file: https://egmont.sharepoint.com/:x:/r/sites/Praxis-softwaregruppen/Shared%20Documents/Kunder/KS/Backporting/Riskanalysis/Security%20advisories%20for%204_4_1%20Risk%20analsis.xlsx?d=wd5aaa50c5edc4ec5ae3a9b7664448874&csf=1&web=1&e=SxKVs5 

There are only 5 issues to estimate. - the time used must be noted. 
One of the issues 81774 you need to look into as its more technical. 
Files for the test is also included in sharepoint. Ask if theres any questions

**Comment by frederikmillingpytlick** [comment]
@neeesn I've updated the excel sheet

**Comment by neeesn** [comment]
@frederikmillingpytlick The want all the changes backported except from the one according BBB since they doesnt use it. 

"Vi har besluttet at vi ønsker å backporte alle bortsett fra den med Big Blue Button, da vi ikke bruker BBB i KS Læring."

**Comment by frederikmillingpytlick** [comment]
@neeesn I've made a new branch with the patches, ready for testing.
