### ISSUE TITLE
Backport Security patches Moodle 4.4.2

### ISSUE THREAD

**Issue by neeesn** [praxisdigital/moodle-kslaring#4]
Different patches that needs to be estimated in time. 
Big one this time - See if theres any unnessesary updates amonong them.

[Security advisories for 4_4_2 Risk analysis.xlsx](https://github.com/user-attachments/files/16578252/Security.advisories.for.4_4_2.Risk.analysis.xlsx)

**Comment by frederikmillingpytlick** [comment]
@neeesn I've made my additions :)

[Security.advisories.for.4_4_2.Risk.analysis (edited).xlsx](https://github.com/user-attachments/files/16598718/Security.advisories.for.4_4_2.Risk.analysis.xlsx)

**Comment by neeesn** [comment]
Afventer svar fra KS

**Comment by neeesn** [comment]
Hei Henrik. 
Vi har sett gjennom og vurdert innspillene deres nå, og har besluttet å gi tommel opp for backporting av alle de sakene dere nevner i Security.advisories.for.4_4_2.Risk.analysis

@frederikmillingpytlick du kan godt gå igang med at backporte.

**Comment by neeesn** [comment]
WE SHALL NOT BACKPORT BBB (BigBlueButton) ISSUES.

Hei igjen. Etter nærmere ettertanke ser vi at det ikke er nødvendig å backporte Big Blue Button-saken, siden vi ikke bruker BBB. Men resten kan backportes 🙂

**Comment by frederikmillingpytlick** [comment]
@neeesn I've backported alle issues except the following:
https://tracker.moodle.org/browse/MDL-82633 - This is only relevant in Moodle 4.4
https://tracker.moodle.org/browse/MDL-79541 - This wasn't easily backportable and I'm unsure whether it is even relevant to backport after looking deeper into it
